Bundle/CoreBundle/Resources/public/js/input-kaede/classie.js
Bundle/CoreBundle/Resources/style/less/bricks/bricks.less
Bundle/CoreBundle/Resources/style/less/bricks/vic-input-kaede.less
Bundle/CoreBundle/Resources/style/less/layouts/login.less
Bundle/CoreBundle/Resources/style/less/parameters/parameters.less
Bundle/CoreBundle/Resources/style/less/parameters/vic-input-kaede.less
Bundle/CoreBundle/Resources/translations/victoire.fr.xliff
Bundle/UserBundle/Resources/views/Security/login.html.twig
Bundle/UserBundle/Resources/views/layout.html.twig

kaede-input Feature/login

---

Bundle/CoreBundle/Entity/Link.php

@lenybernard requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/Victoire/victoire/

Scrutinizer Auto-Fixes

---

Bundle/WidgetBundle/Twig/LinkExtension.php

This fix the missing active class for menu items

$attr should be passed as reference to be updated

---

.gitignore
Tests/test.sh

execute sh ./Tests/test.sh will download composer, install vendors, run a server, setup the DB and execute unit and behat tests for victoire

add automate tests script

---

Bundle/UserBundle/Resources/views/layout.html.twig

We need to use asset() in twig file rather than a direct call to file.

Use "asset()" rather than a direct call to file

---

Tests/Features/Context/VictoireContext.php
Tests/Features/WidgetMap/widgetMap.feature
Tests/Functionnal/src/Victoire/Widget/ForceBundle/Resources/translations/messages.fr.xliff

The existing test was not working.
This method is simpler and only use one xpath query to finalize shouldPrecede assertion

Fix shouldPrecede assert

---

Bundle/CoreBundle/Helper/ViewHelper.php

Retrieve only allowed entitiesPage for its BEP during viewsReferences generation

---

Bundle/AnalyticsBundle/Helper/AnalyticsViewHelper.php
Bundle/AnalyticsBundle/Repository/BrowseEventRepository.php
Bundle/BusinessEntityPageBundle/Helper/BusinessEntityPageHelper.php
Bundle/BusinessEntityPageBundle/Resources/config/services.yml
Bundle/PageBundle/Controller/BasePageController.php
Bundle/WidgetBundle/Twig/LinkExtension.php

Use viewReferences to find best patternId and add method to AnalyticsBundle

---

Bundle/TwigBundle/Controller/ExceptionController.php

actually, if it does contain an extension

Check uri to be sure to not boot kernel if we guess it's a file resource

---

Bundle/BlogBundle/Controller/BlogController.php
Bundle/CoreBundle/Helper/ViewCacheHelper.php
Bundle/CoreBundle/Helper/ViewHelper.php
Tests/Features/BusinessEntityPage/create.feature
Tests/Features/Context/VictoireContext.php
Tests/test.sh

Fix bugs on viewReference generation, on blog route and on behat tests

---

Bundle/QueryBundle/Helper/QueryHelper.php
Bundle/WidgetBundle/Model/WidgetManager.php
Tests/Features/Widget/edit.feature
Tests/Functionnal/src/Acme/AppBundle/Entity/Jedi.php
Tests/test.sh

Add orderBy, fix and add behat tests

---

Bundle/WidgetBundle/Entity/Widget.php

... to be able to have different identifier for cms_slot_widgets especially for overriden widgets

add childrenSlot column

---

Bundle/CoreBundle/Helper/ViewHelper.php
Bundle/CoreBundle/Manager/Chain/ViewManagerChain.php

When cleaning views references, be sure the same id virtual page found are for the same entityNamespace

[VICMS-676] ID collision

---

Bundle/BusinessPageBundle/Helper/BusinessPageHelper.php
Bundle/PageBundle/Controller/BasePageController.php
Bundle/WidgetBundle/Resources/config/services.yml
Bundle/WidgetBundle/Twig/LinkExtension.php

Instead of Doctrine cache entity name

Use EntityManager in BusinessPageHelper to get correct entity name

---

Bundle/MediaBundle/Resources/translations/messages.en.xliff
Bundle/MediaBundle/Resources/translations/messages.es.xliff
Bundle/MediaBundle/Resources/translations/messages.fr.xliff
Bundle/MediaBundle/Resources/translations/victoire.en.xliff
Bundle/MediaBundle/Resources/translations/victoire.es.xliff
Bundle/MediaBundle/Resources/translations/victoire.fr.xliff
Bundle/WidgetBundle/Form/WidgetStyleType.php

Deleted useles helper.blocks in widgetBundle

Added more translation in MediaBundle

---

Bundle/BlogBundle/Resources/translations/victoire.en.xliff
Bundle/BlogBundle/Resources/translations/victoire.es.xliff
Bundle/BlogBundle/Resources/translations/victoire.fr.xliff
README.md
composer.json

Update Composer : branch-alias : 1.3.x-dev & added suggest widgets

---

Bundle/CoreBundle/Listener/ViewCssListener.php
Bundle/CoreBundle/Route/RouteLoader.php

fix cssHash for virtual BP and expose victoire_core_page_show_by_id route

---

Bundle/BlogBundle/Controller/BlogController.php
Bundle/BlogBundle/Form/ArticleSettingsType.php
Bundle/BlogBundle/Form/BlogCategoryType.php
Bundle/PageBundle/Resources/translations/victoire.en.xliff
Bundle/PageBundle/Resources/translations/victoire.es.xliff
Bundle/PageBundle/Resources/translations/victoire.fr.xliff
Bundle/SitemapBundle/Resources/views/Sitemap/sitemap.xml.twig
Tests/bootstrap.php

Change Date format in Sitemap

---

Bundle/I18nBundle/Resolver/LocaleResolver.php
Bundle/I18nBundle/Route/I18nRouteLoader.php

It does avoid resources not found requests to enter in the cms routes

Add _locale requirements for i18n Route loader

---

Bundle/BlogBundle/Controller/BlogController.php
Bundle/BlogBundle/Resources/views/Blog/Tabs/_links.html.twig
Bundle/BlogBundle/Resources/views/Blog/Tabs/content.html.twig
Bundle/BlogBundle/Resources/views/Blog/Tabs/nav.html.twig
Bundle/BlogBundle/Resources/views/Blog/feed.rss.twig
Bundle/SeoBundle/Resources/views/_meta.html.twig

fix https://github.com/Victoire/victoire/issues/339

add Blog RSS feed

---

Bundle/CoreBundle/Resources/script/ngApp/directives/widget.js
Bundle/CoreBundle/Resources/views/Widget/show.html.twig

use angular to inject the hover link

---

Bundle/AnalyticsBundle/Controller/BrowseEventController.php
Bundle/CoreBundle/Route/RouteLoader.php

log and return a null 202 response when an heart beat

---

Bundle/CoreBundle/Resources/public/js/edit/widget.js
Bundle/CoreBundle/Resources/views/Widget/Form/stylize.html.twig
Bundle/WidgetBundle/Controller/WidgetController.php

This PR fixes #439 #440 and a bug when adding a quantum on a widget at first position in a slot

quantum fixes

---

Bundle/BlogBundle/Controller/ArticleController.php
Bundle/BlogBundle/Controller/BlogController.php
Bundle/TemplateBundle/Controller/TemplateController.php
Bundle/TwigBundle/Controller/ErrorPageController.php
Bundle/WidgetBundle/Twig/LinkExtension.php

getLocale no longer exists, use getCurrentLocale instead

kick getLocale usages

---

Bundle/CoreBundle/Resources/public/js/edit/widget.js
Bundle/CoreBundle/Resources/views/Widget/Form/_modal.html.twig
Bundle/CoreBundle/Resources/views/Widget/Form/stylize.html.twig
Bundle/FormBundle/Resources/public/js/form.js
Tests/Features/Context/VictoireContext.php

JS bulk action had an issue that posted widget for each form in the modal.
I kicked bulk action to use "update" or "create" action instead, because widget always have at least one quantum

Ensure to post widget form just once

---

Tests/Features/Blog/create.feature
Tests/Features/Blog/delete.feature
Tests/Features/BusinessEntityPage/create.feature
Tests/Features/BusinessEntityPage/delete.feature
Tests/Features/BusinessEntityPage/jedi.feature
Tests/Features/BusinessEntityPage/parentIsPattern.feature
Tests/Features/Page/create.feature
Tests/Features/Page/delete.feature
Tests/Features/Page/seo.feature
Tests/Features/Page/sitemap.feature
Tests/Features/Widget/asynchronousWidget.feature
Tests/Features/Widget/delete.feature
Tests/Features/Widget/edit.feature
Tests/Features/Widget/stilyze.feature
Tests/Features/Widget/widget.feature.todo
Tests/Features/WidgetMap/widgetMap.feature
Tests/Features/authentication.feature
Tests/Functionnal/app/config/config_test.yml
behat.yml.dist

This PR avoids the time consuming login step by enabling http authentication

Use http authentication in tests

---

Bundle/CoreBundle/Resources/style/less/ugly.less
Bundle/CoreBundle/Resources/views/Widget/new.html.twig
Bundle/PageBundle/Twig/Extension/PageExtension.php

This pr cleans up widget creation/update forms by setting the criterias form items in bottom and collapsed by default.
Before : http://grab.by/R19k
After : ![after](http://new.tinygrab.com/09b6643d7da974e4841becf97b9811032f52db90cc.png)

improve criterias style

---

Bundle/CoreBundle/Form/CriteriaCollectionType.php
Bundle/CoreBundle/Repository/ViewRepository.php
Bundle/MediaBundle/Entity/Media.php
Bundle/MediaBundle/Form/File/FileType.php
Bundle/MediaBundle/Helper/File/FileHandler.php
Bundle/ViewReferenceBundle/Helper/ViewReferenceHelper.php

use a locale param to define manually the reference locale part of a view ref id    

---

Bundle/PageBundle/Helper/PageHelper.php

Used in the search widget to display only accessible pages

make the checkPageValidity public

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Bugfix
Fix the markdown syntax for issues and PR templates
NO

fix markdown for github templates

---

Bundle/WidgetBundle/Resolver/BaseWidgetContentResolver.php

Bugfix
Inject entity in the widget view even in query and business entity mode
NO

inject entity in the widget view even in query and business entity mode

---

Bundle/BlogBundle/Entity/Article.php

feature
This PR brings support of user avatar in image widget
NO

make user avatar imageable

---

Bundle/WidgetMapBundle/Manager/WidgetMapManager.php

Bugfix
Clean the code by adding a missing comma
NO

:shirt: clean code style

---

Bundle/QueryBundle/Entity/QueryTrait.php
Bundle/WidgetBundle/Entity/Traits/StyleTrait.php
Bundle/WidgetBundle/Entity/Traits/StyleTraits/StyleLGTrait.php
Bundle/WidgetBundle/Entity/Traits/StyleTraits/StyleMDTrait.php
Bundle/WidgetBundle/Entity/Traits/StyleTraits/StyleSMTrait.php
Bundle/WidgetBundle/Entity/Traits/StyleTraits/StyleXSTrait.php

Improvement
Fix some alerts from sensio labs insight
NO

add missing uses statments

---

README.md

Documentation fix
Fix link to CriteriaBundle
NO

README.md: Fix link to CriteriaBundle

---

Bundle/CoreBundle/Resources/script/linkModal.js
UPGRADE-v2.md

Link modal javascript fixes

---

Bundle/CoreBundle/Entity/View.php

View's children must be set and persist when setting a View's parent excepted when View is a VirtualBusinessPage
Bugfix
NO

Fix View's children missing relation

---

Bundle/CoreBundle/Entity/View.php

Bugfix 
Fix error when change the page tree
NO

check if parent is not null

---

Bundle/CoreBundle/Resources/views/Layout/layout.html.twig

feature
This PR allow to use js variables earlier in layout
NO

Js variables adminLocale, locale and debug must be defined at the beginning of layout

---

Bundle/SitemapBundle/Resources/script/sitemap.js

Add missing locale to victoire_sitemap_reorganize route used with FOS js routing

---

.github/CONTRIBUTE.md
Bundle/AnalyticsBundle/README.md
Bundle/BlogBundle/Resources/translations/victoire.en.xliff
Bundle/BusinessEntityBundle/README.md
Bundle/BusinessEntityBundle/Resources/translations/victoire.en.xliff
Bundle/CoreBundle/Resources/doc/SETUP.md
Bundle/CoreBundle/Resources/translations/victoire.en.xliff
Bundle/MediaBundle/Resources/translations/messages.en.xliff
Bundle/MediaBundle/Resources/translations/victoire.en.xliff
Bundle/PageBundle/Resources/translations/victoire.en.xliff
Bundle/ViewReferenceBundle/README.md
Bundle/ViewReferenceBundle/Resources/doc/redis.md
Bundle/WidgetBundle/Resources/doc/themes.md
Bundle/WidgetMapBundle/README.md
Bundle/WidgetMapBundle/Resources/doc/WidgetMap.md
README.md
Tests/Functionnal/src/Victoire/Widget/ForceBundle/README.md
Tests/Functionnal/src/Victoire/Widget/LightSaberBundle/README.md

Feature
Fix typos and remove unnecessary spaces, see https://en.wikipedia.org/wiki/Colon_(punctuation)#Usage for explanation
NO

Fix typos, remove space before colon

---

Bundle/CoreBundle/Resources/doc/SETUP.md
README.md

Bugfix: documentation
Fix the issue [#691](https://github.com/Victoire/victoire/issues/691)

Setup guide: suggest to change minimum stability of Composer

---

.github/PULL_REQUEST_TEMPLATE.md

Documentation
Fix the issue [#xxx](https://github.com/Victoire/victoire/issues/xxx)
OR
This PR brings improvement of the GitHub template of PRs.
NO

PR template: Add a "documentation" option

---

Bundle/CoreBundle/Resources/views/Widget/Form/stylize/_responsiveTab.html.twig
Bundle/CoreBundle/Resources/views/Widget/Form/stylize/responsive.html.twig

fix responsive tab for style modal

---

Bundle/WidgetBundle/Twig/LinkExtension.php

Code documentation
This PR improves documentation of the `LinkExtension#victoireLinkUrl()` method.
NO

Fix method documentation of victoireLinkUrl()

---

Bundle/WidgetBundle/Twig/LinkExtension.php

feature
This PR add a new Twig function to check if a given Link is active for current request. It allow us to define active class in all kind of html markup.
NO

Add Twig function is_vic_link_active to LinkExtension

---

Bundle/WidgetBundle/Controller/WidgetController.php

feature
This PR enabled victoire page debug if kernel debug is enabled
NO

Allow to access victoire debug if debug enable

---

composer.json

Bugfix
Force FOSUserBundle to avoid compatibility issues.
NO

Force FOSUserBundle dependency on v2.0.0-beta1

---

Bundle/BlogBundle/Entity/Blog.php
Bundle/BlogBundle/Resources/config/services.yml

Bugfix
Fix the issue [#565](https://github.com/Victoire/victoire/issues/565)
NO

Blog extend Page and add menu listener for SEO

---

Bundle/CoreBundle/Resources/views/Widget/new.html.twig

feature
This PR brings a twig info block on new widget view
NO

Add info block in new widget view

---

Bundle/CoreBundle/Resources/config/assetic_injector.json

Bugfix
Fix angular when using asseting injector
NO

replace http by https to get angular sanitize

---

Bundle/BlogBundle/Form/ArticleType.php

Feature
This PR improve the form of the article with display only ROLE_VICTOIRE users in author field.

Only show author with ROLE_VICTOIRE in article type

---

Bundle/CoreBundle/Form/EntityProxyFormType.php
Bundle/CoreBundle/Resources/config/forms.yml

Entity proxy: Filter by available translations

---

Bundle/BlogBundle/VictoireBlogEvents.php

CREATE_ARTICLE event: s/aricle/article/

---

Tests/Features/Blog/edit.feature

Bugfix for the test environment.
Fixes  #770.
NO

Fix test of slug update of an article

---

Tests/Functionnal/app/AppKernel.php

Feature
This PR update the `cleanupContainer()` method in `AppKernel.php`.
NO

:green_heart: AppKernel: Use new cleanupContainer()

---

.github/PULL_REQUEST_TEMPLATE.md

instead of creating a link.
This allows to close an issue from the PR, see: https://github.com/blog/1506-closing-issues-via-pull-requests
and https://help.github.com/articles/closing-issues-via-commit-messages/
Feature
This PR improves the template used by Pull Requests.
NO

PULL_REQUEST_TEMPLATE.md: Use issue number

---

Bundle/CoreBundle/Resources/config/services.yml
Bundle/CoreBundle/Twig/Extension/GlobalsExtension.php
Bundle/CoreBundle/Twig/Extension/RoutingExtension.php

Fix extention typo (with extension)

---

Bundle/BlogBundle/Filter/CategoryFilter.php
Bundle/BlogBundle/Repository/CategoryRepository.php
CHANGELOG.md

Feature
This PR removes a dependency on a fork.
It reverts #270
YES|NO?

:fire: Remove "infinite_form_choice_tree" form type

---

Bundle/BusinessPageBundle/Controller/BusinessTemplateController.php
Bundle/PageBundle/Helper/PageHelper.php
Bundle/WidgetBundle/Resolver/WidgetResolver.php
Tests/Functionnal/src/Victoire/Widget/ForceBundle/Form/WidgetForceType.php
Tests/Functionnal/src/Victoire/Widget/LightSaberBundle/Form/WidgetLightSaberType.php

Bugfix
Fix some check style issues
NO

:rotating_light: CS fixes

---

composer.json

Feature
Victoire must not require sensio/distribution-bundle
YES

:arrow_down: remove sensio/distribution-bundle

---

install.sh

Bugfix
My bad, i pushed a local sh file on a previous PR.
NO

Remove install.sh file

---

UPGRADE-v2.md

Documentation
This PR brings SQL command to execute for upgrade.
NO

Update documentation for Upgrade 2.2.18

---

bisect

:fire: Remove unused bisect file

---

Bundle/BusinessPageBundle/Controller/BusinessTemplateController.php
Bundle/BusinessPageBundle/Resources/views/BusinessEntity/index.html.twig
Bundle/CoreBundle/Resources/public/js/edit/widget.js
Bundle/CoreBundle/Resources/views/Widget/Form/new.html.twig
Bundle/CoreBundle/Resources/views/Widget/Form/new_partial.html.twig
Bundle/CoreBundle/Resources/views/Widget/Form/stylize.html.twig
Bundle/CoreBundle/Resources/views/Widget/Form/tab.html.twig
Bundle/SeoBundle/Resources/views/Form/localeTabs.html.twig
Bundle/WidgetBundle/Controller/WidgetController.php
Bundle/WidgetMapBundle/Warmer/WidgetDataWarmer.php
Tests/Features/Context/VictoireContext.php
Tests/Features/Widget/editQuantum.feature

Bugfix
Fixes #732 
And an unknown issue about WidgetDataWarmer and multiple criterias
NO

Widget quantum issue on template

---

Bundle/CoreBundle/Command/WidgetCssGenerateCommand.php
Bundle/CoreBundle/Listener/ViewCssListener.php
Bundle/PageBundle/Helper/PageHelper.php
Tests/Features/Widget/stilyze.feature
doc/setup.md

Bugfix | documentation
Fixes #762 
NO

Fix first loading of View with CSS not up to date

---

README.md
doc/setup.md

Documentation
This PR improves documentation of setup
NO

Update setup documentation

---

Bundle/UIBundle/Command/FetchAssetsCommand.php
README.md

Bugfix | documentation
Add UIBundle to documentation and fix FetchAssetCommand
NO

Documentation & FetchAssetCommand fix

---

Bundle/PageBundle/Helper/PageHelper.php
Bundle/WidgetBundle/Command/CreateWidgetCommand.php

Feature
This PR fixes a typo.
NO

Fix typos: "it's [noun]" → "its [noun]"

---

README.md

:memo: Documentation
This PR improves documentation of how maintenance is performed, by explaining how different branches receive patches.
NO

README: Add "Maintenance" section

---

Bundle/BlogBundle/Entity/Blog.php

Missing method blog entity

---

Bundle/CoreBundle/Command/TestBundlesKernelAdderCommand.php
Tests/App/app/AppKernel.php

Add TestBundlesKernelAdderCommand for tests purposes

---

Bundle/WidgetMapBundle/Resources/doc/WidgetMap.md

documentation
This PR improves documentation of widgetmap readme
NO

Update ReadMe - markdown

---

composer.json

Upgrade FOS User to 2.0 and update test-suite

---

Bundle/CoreBundle/Resources/config/assetic_injector.json
Bundle/CoreBundle/Resources/views/Layout/layout.html.twig
Tests/Functionnal/app/config/config_base.yml
behat.yml.dist
composer.json

Bugfix
This PR avoid assetic to compile cdn javascript assets.
NO

removes from assetic_injector cdn assets

---

Bundle/CoreBundle/Resources/translations/victoire.en.xliff
Bundle/CoreBundle/Resources/translations/victoire.es.xliff
Bundle/CoreBundle/Resources/translations/victoire.fr.xliff
Bundle/CoreBundle/Resources/views/Widget/Form/_modal.html.twig
Tests/Features/BusinessEntityPage/parentIsPattern.feature
Tests/Features/Context/JavascriptContext.php
Tests/Features/Context/VictoireContext.php
Tests/Features/Widget/create.feature
Tests/Features/WidgetMap/widgetMapTemplate.feature

Add Behat steps for Widgets tests

---

Tests/Features/Context/VictoireContext.php
behat.yml.dist

Add additional Contexts from external tested Bundles

---

Bundle/CoreBundle/Event/WidgetFlushedEvent.php
Bundle/CoreBundle/VictoireCmsEvents.php
Bundle/WidgetBundle/Builder/WidgetFormBuilder.php
Bundle/WidgetBundle/Event/WidgetFormEvents.php
Bundle/WidgetBundle/Event/WidgetFormPostCreateEvent.php
Bundle/WidgetBundle/Event/WidgetFormPreCreateEvent.php
Bundle/WidgetBundle/Model/WidgetManager.php
Bundle/WidgetBundle/Resources/config/services.yml
UPGRADE-v2.md

Dispatch new events for Widget FormBuilder creation and flush

---

Tests/App/src/Acme/AppBundle/Controller/JediController.php
Tests/App/src/Acme/AppBundle/Resources/views/Jedi/indexFront.html.twig
Tests/App/src/Acme/AppBundle/Resources/views/Jedi/showFront.html.twig

Add routes in JediController for tests purposes

---

Tests/Features/Context/VictoireContext.php

Trigger resetViewReferences on Alice AfterBackground hook

---

Bundle/CoreBundle/Entity/View.php
Bundle/I18nBundle/Entity/ViewTranslation.php
Bundle/PageBundle/DependencyInjection/VictoirePageExtension.php
Bundle/WidgetMapBundle/Entity/WidgetMap.php
Tests/App/src/Acme/AppBundle/DataFixtures/Fixtures/ORM/Character/template.yml
Tests/App/src/Acme/AppBundle/Entity/Character.php
Tests/App/src/Acme/AppBundle/Entity/Jedi.php
Tests/App/src/Acme/AppBundle/Entity/Mercenary.php
Tests/Features/Context/VictoireContext.php
behat.yml.dist

Serialize ViewTranslations for WidgetSearchBundle

---

Bundle/BlogBundle/Entity/Article.php

Bugfix
Fixes #722 
Automatically set the publishedAt property when article is publish
NO

Fix publishedAt property when article is publish

---

Bundle/PageBundle/DependencyInjection/VictoirePageExtension.php

Use parameter to set elastica pages index

---

Bundle/CoreBundle/Resources/public/js/edit/widget.js
Bundle/CoreBundle/Resources/views/Widget/Form/new_partial.html.twig
Bundle/CoreBundle/Resources/views/Widget/Form/stylize.html.twig
Bundle/PageBundle/DependencyInjection/VictoirePageExtension.php
Bundle/WidgetBundle/Builder/WidgetFormBuilder.php
Bundle/WidgetBundle/Controller/WidgetController.php
Bundle/WidgetBundle/Model/WidgetManager.php
Tests/App/app/Resources/VictoireCoreBundle/views/Layout/defaultLayout.html.twig
Tests/App/app/config/config_base.yml

Add bazinga and alertify in test env, transform quantum from integer to string

---

Bundle/BlogBundle/Controller/BlogController.php
Bundle/BlogBundle/Form/ChooseBlogType.php

Reload first blog after locale change

---

Bundle/SitemapBundle/Domain/Export/SitemapExportHandler.php
Bundle/SitemapBundle/Resources/config/services.yml

Fix SitemapExportHandler dependency injection issue

---

Bundle/WidgetBundle/Cache/WidgetCache.php
Bundle/WidgetBundle/Command/ClearWidgetCacheCommand.php

Bugfix
Create a command to clear widget cache.
Avoid to clear all redis DB in WidgetCache.php clear function.
NO

widget cache

---

doc/setup.md

Remove DoctrineFixturesBundle from AppKernel declaration in doc. Not a Victoire dependencies

Remove false Victoire Dependencies

---

Bundle/CoreBundle/Entity/View.php
Bundle/PageBundle/Entity/BasePage.php
Bundle/SitemapBundle/Resources/views/Sitemap/_sitemapItem.html.twig

Get only published pages in sitemap children call

---

Bundle/BlogBundle/Resources/views/Blog/_blogItem.html.twig

Bugfix
_blogItem.html.twig was causing an issue when no blog was created

Avoid twig error on BLog form when no blog exist

---

Bundle/WidgetBundle/Controller/WidgetController.php

give the quantum variable to twig as it's required

---

Bundle/BlogBundle/Filter/CategoryFilter.php

Feature
This PR brings support of filtering on blog categories in a multiple way (checkbox instead of radio).
YES

allow to have multiple categories blog filter

---

Bundle/CoreBundle/Resources/public/js/edit/widget.js
Bundle/CoreBundle/Resources/views/Widget/Form/new_partial.html.twig
Bundle/CoreBundle/Resources/views/Widget/Form/stylize.html.twig
Bundle/WidgetBundle/Builder/WidgetFormBuilder.php
Bundle/WidgetBundle/Controller/WidgetController.php
Bundle/WidgetBundle/Model/WidgetManager.php
Tests/Features/Widget/stilyze.feature

Fix widget style with quantum

---

README.md

documentation
This PR fixes the rendering of the readme.
NO

Fix the Markdown syntax of the README file

---

CHANGELOG.md

Documentation
Remove misleading text from changelog.
NO

Update changelog with 2.2.16

---

composer.json

Temporary Bugfix
Fixes #951 Avoid to crash because of symfony 3.2.10
NO

restrict to symfony 3.2.9 as 3.2.10 is causing trouble

---

Bundle/BusinessEntityBundle/Reader/BusinessEntityCacheReader.php

Bugfix
Fixes a notice that crash website in `dev` environment:
> Notice: Undefined index: receiverProperties
> 
> Stack Trace
> 
> in vendor/victoire/victoire/Bundle/BusinessEntityBundle/Reader/BusinessEntityCacheReader.php at line 67
YES|NO?

Fix "Notice: Undefined index: receiverProperties"

---

Bundle/BlogBundle/Entity/Tag.php

feature
This PR brings support of Tags for use them as BusinessEntity.
NO

add BusinessProperties for Blog Tag

---

Bundle/BlogBundle/Entity/BlogCategory.php

Bugfix
Add missing business property for blog category generation
NO

fixed missing business property for blog category

---

Bundle/BlogBundle/Entity/Category.php

Bugfix
fixed missing business property for blog category in Victoire 2.3
NO

added missing business property for blog category

---

Bundle/CoreBundle/Command/WidgetCssGenerateCommand.php

to prevent doctrine memory leaks with a lot of views
feature
Improve victoire:widget-css:generate for project with many views.
NO

flush entities by spool

---

Bundle/WidgetBundle/Model/WidgetManager.php
Bundle/WidgetMapBundle/Entity/WidgetMap.php
Tests/Features/WidgetMap/widgetMapTemplate.feature

Bugfix 
Change method call order to avoid missing cascade persist issue
NO

persist after widget delete in order to cascade persist new widget map 

---

Bundle/BlogBundle/Resources/views/Blog/feed.rss.twig

Bugfix 
fix rss error caused by wrong attribut name for pageseo parameter
NO

Change attribut name for page seo description in rss template

---

Bundle/BlogBundle/Entity/Category.php
Bundle/BlogBundle/Filter/CategoryFilter.php
Bundle/BlogBundle/Filter/DateFilter.php
Bundle/BlogBundle/Filter/TagFilter.php
Bundle/CoreBundle/Command/WidgetCssGenerateCommand.php
Bundle/CoreBundle/Entity/View.php
Bundle/MediaBundle/Entity/Folder.php
Bundle/MediaBundle/Helper/Menu/MenuItem.php
Bundle/WidgetMapBundle/Entity/WidgetMap.php
composer.json

Bugfix
Remove deprecated empty_values 
NO

remove deprecated empty_values and choices as values for Filters

---

Bundle/WidgetMapBundle/Warmer/WidgetDataWarmer.php

Bugfix
Fixes queries in WidgetDataWarmer for ordered entities
This is a cherry pick of #915 on 2.2 branch
NO

implement OrderBy support in widgetDataWarmer

---

circle.yml

Feature
Upgrade version of PHP used on CircleCI.
NO

CircleCI: Use PHP 7.1.9

---

.gitignore
Bundle/BusinessEntityBundle/Annotation/AnnotationDriver.php
composer.json

Bugfix
Fixes #951 
Replaces #961 (I rebased the branch from @Yoann-TYT on the 2.3 branch)
MAYBE

Suggest using other method to get classnames rebase

---

dependencies.md
doc/setup.md

Documentation
This PR improves documentation of dependencies, after #1028 was merged.
NO

2.3 update documentation

---

Bundle/QueryBundle/Helper/QueryHelper.php

Bugfix
Fixes #931
Remove duplicated code `is_object($this->getCurrentUser())` in conditions.
NO

931 remove unreachable code in query helper

---

Tests/Features/Seo/Error404/create.feature
Tests/Features/Seo/Error404/modal.feature
Tests/Features/Seo/Error404/redirect.feature
Tests/Features/Seo/Redirection/create.feature
Tests/Features/Seo/Redirection/delete.feature
Tests/Features/Seo/Redirection/modify.feature

Fix tests after #1024
Bugfix
Fixes #1041 
NO

Fixes #1041: Fix Seo features by using English locale

---

Bundle/BlogBundle/Form/ChooseBlogType.php
Bundle/BlogBundle/Form/DataTransformer/EntityToIdTransformer.php
Bundle/BlogBundle/Repository/BlogRepository.php

Checkstyle
Fixes code style (Codacy build)
NO

Codacy patch

---

Bundle/BlogBundle/Controller/ArticleController.php
Bundle/BlogBundle/Controller/BlogController.php
Bundle/BusinessPageBundle/Controller/BusinessTemplateController.php
Bundle/CoreBundle/Controller/UIController.php
Bundle/MediaBundle/Controller/ChooserController.php
Bundle/MediaBundle/Controller/FolderController.php
Bundle/MediaBundle/Controller/MediaController.php
Bundle/MediaBundle/Resources/views/Chooser/choosershownode.html.twig
Bundle/PageBundle/Controller/PageController.php
Bundle/SeoBundle/Controller/PageSeoController.php
Bundle/SitemapBundle/Controller/SitemapController.php
Bundle/UIBundle/Controller/StyleguideController.php
Bundle/WidgetBundle/Controller/WidgetController.php
composer.json

Bugfix 
Fixes #1047 
Remove usage of @Template annotation in victoire for compatibility with sensio/framework-extra-bundle version 3, 4, 5
It's more compliant with symfony best practices (http://symfony.com/doc/current/best_practices/controllers.html#template-configuration) 
NO

remove usage of @Template annotation

---

doc/setup.md

documentation
I was fallowing this guide and kept having this error
```
[RuntimeException]                                                         
An error occurred when executing the "'cache:clear --no-warmup'" command:  
In ParameterBag.php line 102:                                              
You have requested a non-existent parameter "templating.engines". 
```
So I just added two lines to config.yml
No

Fixed config.yml in setup.md

---

Bundle/BlogBundle/Controller/BlogController.php
Bundle/BlogBundle/Repository/ArticleRepository.php
Bundle/BlogBundle/Resources/translations/victoire.en.xliff
Bundle/BlogBundle/Resources/translations/victoire.es.xliff
Bundle/BlogBundle/Resources/translations/victoire.fr.xliff
Bundle/BlogBundle/Resources/views/Blog/Tabs/_articles.html.twig
Bundle/BlogBundle/Resources/views/Blog/Tabs/_drafts.html.twig
Tests/Features/Blog/blogI18n.feature
Tests/Features/Blog/create.feature

Feature
This PR order Articles by createdAt date.
NO

Split articles and drafts in blog and order by date

---

Bundle/BlogBundle/Controller/BlogController.php
Bundle/BlogBundle/Repository/ArticleRepository.php
Bundle/BlogBundle/Resources/translations/victoire.en.xliff
Bundle/BlogBundle/Resources/translations/victoire.es.xliff
Bundle/BlogBundle/Resources/translations/victoire.fr.xliff
Bundle/BlogBundle/Resources/views/Blog/Tabs/_articles.html.twig
Bundle/BlogBundle/Resources/views/Blog/Tabs/_drafts.html.twig
Tests/App/src/Acme/AppBundle/DataFixtures/Fixtures/ORM/Blog/article.yml
Tests/App/src/Acme/AppBundle/DataFixtures/Fixtures/ORM/Blog/article_i18n.yml
Tests/App/src/Acme/AppBundle/DataFixtures/Fixtures/ORM/Blog/businessPage.yml
Tests/Features/Blog/articles.feature
Tests/Features/Blog/blogI18n.feature

feature
This PR split articles and drafts in blog.
NO

WIP: separate drafts articles in an other tabs and orderBy date DESC

---

Bundle/BlogBundle/Controller/BlogController.php
Bundle/BlogBundle/Repository/ArticleRepository.php
Bundle/BlogBundle/Resources/views/Blog/feed.rss.twig

Bugfix
Fixes #923 
Fixes #992
NO

Hides unpublished articles in blog feeds

---

Bundle/SitemapBundle/Resources/views/Sitemap/sitemap.xml.twig

Fixes twig syntax error

---

Bundle/PageBundle/Helper/PageHelper.php

feature
This PR brings support of permanent redirections (301) to SeoBundle Redirections
NO

[2.3] set redirect response status to permanent

---

Bundle/CoreBundle/Annotations/BusinessProperty.php
Bundle/CoreBundle/Annotations/ReceiverProperty.php

Bugfix
Fixes PHP 7.2 syntax array manipulation functions need array and that makes sense :)
YES

fix php 7.2 syntax

---

Bundle/BusinessPageBundle/Builder/BusinessPageBuilder.php

Bugfix do not use timestamp businessTemplate of template
NO

do not use timestamp businessTemplate of template

---

Bundle/PageBundle/Helper/PageHelper.php
Bundle/WidgetBundle/Twig/LinkExtension.php

Fixed the bug related to the locale. The "findPageByReference" method is called by a WidgetLink that redirects to a page in another locale than the view.
This changes the current locale of the business entity.
Bugfix
NO

Fixed the bug related to the locale.

---

Makefile
Tests/App/app/config/config_dev.yml
composer.json
doc/backend-contribution.md

feature | documentation
Easier way to start a raw victoire
NO

add a makefile

---

Bundle/CoreBundle/Resources/views/Widget/show.html.twig
Tests/App/src/Acme/AppBundle/DataFixtures/Seeds/ORM/User/user.yml
Tests/Features/Context/VictoireContext.php
Tests/Features/Widget/edit.feature

Feature 
Victoire basic user can't edit the original widget from a child page.
NO

Update authorization to edit widget

---

doc/setup.md

documentation
Fix inconsistent seeds
NO

Fix inconsistent seeds

---

Bundle/CoreBundle/Repository/ViewRepository.php
Bundle/SitemapBundle/Command/GenerateCommand.php
Bundle/SitemapBundle/Controller/SitemapController.php
Bundle/SitemapBundle/Domain/Export/SitemapExportHandler.php
Bundle/SitemapBundle/Resources/config/services.yml
Bundle/SitemapBundle/Resources/views/Sitemap/sitemap.xml.twig

Bugfix & feature
Backport #1054, #1059 and #1095 in 2.3 branch.
NO

Sitemap cache 2.3

---

Bundle/BlogBundle/Entity/Blog.php

Bugfix
Fixes #923 (for 2.3 branch)
NO

Hides unpublished article in feed

---

Bundle/WidgetBundle/Cache/WidgetCache.php

Bugfix
Generate an hash with all possible victoire roles to avoid generatin of a mutualized hash between different type of victoire administrators
NO

Cache sharing issue

---

Bundle/CoreBundle/Resources/views/Layout/layout.html.twig

Added compatibility with print style sheets
NO

Added compatibility with print style sheets
