- Bundle/CoreBundle/Command/LegacyLinkMigratorCommand.php
- Bundle/CoreBundle/Entity/Link.php
- Bundle/WidgetBundle/Entity/Traits/LinkTrait.php
- to run the following command :
```php
console victoire:legacy:linkMigrator
```
- to update every version of widget which use the LinkTrait 
```php
composer update victoire/slider-widget victoire/button-widget victoire/menu-widget
```
If you used LinkTrait in your own widgets, you need to do these things:
- replace linkParameters by link.parameters
> Refactor viclink [BC Break]

- Bundle/CoreBundle/Helper/ViewHelper.php
Lorsqu'on utilisait la méthode vic_business_link, c'est le paramètre viewId qui était recherche dans le fichier viewReferences.xml alors qu'il faut utiliser le paramètre patternId pour les pattern entities
> Use patternId instead of viewId for pattern entities in ViewHelper

- Bundle/CoreBundle/Helper/ViewCacheHelper.php
- Bundle/CoreBundle/Helper/ViewHelper.php
When i was creating a Business Entity, the cache regenerated was wrong. The method call from view cache helper rewrite Business entity page pattern with an entity id.
> fix update to regenerate correct references

- Bundle/CoreBundle/Resources/config/assetic_injector.json
- Bundle/CoreBundle/Resources/script/ngApp/app.js
- Bundle/CoreBundle/Resources/views/backendLayout.html.twig
- Bundle/CoreBundle/Resources/views/layout.html.twig
we can now push extra dependancies in the ngApp with the window.ngDependancies array which is read when boostraped
> remove angular library from victoire-ngApp assetic injector

- Bundle/CoreBundle/Entity/Link.php
- Bundle/CoreBundle/Resources/config/services.yml
- Bundle/CoreBundle/Twig/Extension/CmsExtension.php
- Bundle/PageBundle/Controller/BasePageController.php
- Bundle/PageBundle/Entity/WidgetMap.php
- Bundle/PageBundle/Helper/PageHelper.php
- Bundle/WidgetBundle/Entity/Traits/LinkTrait.php
- Bundle/WidgetBundle/Twig/LinkExtension.php
- Bundle/WidgetMapBundle/Builder/WidgetMapBuilder.php
- Bundle/WidgetMapBundle/Resources/config/services.yml
- Bundle/WidgetMapBundle/Warmer/AssociatedEntityToWarm.php
- Bundle/WidgetMapBundle/Warmer/WidgetDataWarmer.php
Avoid most of the queries launched during template rendering by loading widget's associated entities before rendering.
> Widget Rendering Refactor

- Bundle/BusinessEntityBundle/Reader/BusinessEntityCacheReader.php
Fetch method on cache object doesn't accept default value : get method, yes
If key is not found, $results = false and somes methods after will crash like it : https://github.com/Victoire/victoire/blob/master/Bundle/BusinessEntityBundle/Helper/BusinessEntityHelper.php#L112
> Call get method to use really default value

- Bundle/I18nBundle/Resources/config/services.yml
- Bundle/I18nBundle/Translation/Translator.php
- Bundle/ViewReferenceBundle/Connector/Redis/ViewReferenceRedisTool.php
...instead of injecting useless and buggy requestStack
> Use container to get request locale

- Bundle/QueryBundle/Helper/QueryHelper.php
- Bundle/QueryBundle/Resources/config/services.yml
In some case like, we want to be able to filter the query according to the current user.
Now, we just need to have some BusinessEntity with a User relation and use `:currentUser` in the query input: 
`JOIN item.user WHERE u.id = :currentUser`
> support current user in Query Trait

- Bundle/UserBundle/Resources/views/layout.html.twig
- Tests/Functionnal/app/Resources/views/base.html.twig
This PR allows project to use the default login template without ::base.html.twig
> extends Victoire:Layout:base.html.twig instead of "no more used" ::base.html.twig

- Bundle/WidgetBundle/Renderer/WidgetRenderer.php
In some cases, for example, WidgetRender in BusinessEntity mode with magic variables {{entity.id}} transformed into the real business entity id, then if in the rendered action, we need to flush, it would persist the modified widget which really uncomfortable ;)
> :bug: refresh widget to avoid to flush modified widget

- Bundle/CoreBundle/Repository/ViewRepository.php
Bugfix
remove staticly defined FROM alias in getAll views query
NO
> use query alias instead of static 'page'

- Bundle/PageBundle/Controller/BasePageController.php
- Bundle/WidgetBundle/Twig/LinkExtension.php
Bugfix
The modalLayout is used even if request is not xhr
NO
> :bug: prevent LinkExtension to add modalLayout when request is not xhr

- Bundle/TemplateBundle/Resources/views/Template/index.html.twig
feature
This PR improve the template modal list reading by using template's backendName if set.
NO
> Use Template backendName if set in Template modal list

- Bundle/BusinessEntityBundle/README.md
Documentation
Doctrine annotations should not use curly brackets if only one item is present
NO
> BusinessEntity: Remove curly brackets in annotation

- Bundle/PageBundle/Entity/Traits/WebViewTrait.php
feature
This PR brings improvement of WebViewTrait for authorize to give currentLocale on getUrl.
In some case we search Url for a widget and we must give the locale of target view. 
ex. when we have a widgetFilter on a page who target a list on a different page, we must force locale otherwise getUrl returns defaultTranslation
NO
> Allow insert current locale in getUrl

- Bundle/BusinessEntityBundle/EventSubscriber/BusinessEntitySubscriber.php
- Bundle/QueryBundle/Helper/QueryHelper.php
- Tests/Features/I18n/domainLocaleStragegy.feature
- Tests/Functionnal/src/Acme/AppBundle/Entity/SpaceShip.php
- Tests/Functionnal/src/Acme/AppBundle/Entity/SpaceShipTranslation.php
Bugfix
When checking if a Business Entity is allowed for a businessTemplate, a query is built. 
This query makes a join on translations, but in the case this query is build by a postPersist event, so the translations may be unknown by the entity manager resulting in a false positive for isEntityAllowed method.
The join seemed to be not necessary anymore so this PR removes it
NO
> do not join translations when building the BusinessPage or widget query

- Bundle/MediaBundle/Form/File/FileType.php
Bugfix
The media gallery has an edit functionnality to change image name and file.
Since sf2.8, this feature leaded to a 500 error. 
There was conflict between the form name ("file") and the field name ("file" too) that leads to have all form data replaced by the fields data.
The error thrown was the following:
```
ncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Cannot use object of type Symfony\Component\HttpFoundation\File\UploadedFile as array" at /var/www/[...]/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Csrf/EventListener/CsrfValidationListener.php line 109
```
NO
> media gallery image edit

- Bundle/MediaBundle/Resources/views/Media/create.html.twig
Bugfix
Video type has an "url" field while File type has a "file" field but both use the same twig template. Use automatic form rendering to be compliant with the two types
NO
> use automatic form generation for media

- Bundle/SeoBundle/Entity/PageSeo.php
- Bundle/SeoBundle/Entity/PageSeoTranslation.php
Bugfix
increase the size of the metaTitle to 63 characters
NO
> increase the size of the metaTitle to 65 char

- composer.json
Feature
Fixes #778
When a website is deployed on a production environment, the [`--no-dev` option of Composer](https://getcomposer.org/doc/03-cli.md#install) can be used to skip installation of `require-dev` dependencies. Since fixtures are not necessary on a production environment, `doctrine/doctrine-fixtures-bundle` can be skipped in this context.
NO
> :wrench: Move "doctrine/doctrine-fixtures-bundle" in "require-dev"

- Bundle/WidgetMapBundle/Builder/WidgetMapBuilder.php
- Bundle/WidgetMapBundle/Command/WidgetMapOverwriteValidationCommand.php
- Bundle/WidgetMapBundle/Entity/WidgetMap.php
- Bundle/WidgetMapBundle/Manager/WidgetMapManager.php
- Bundle/WidgetMapBundle/Resolver/WidgetMapChildrenResolver.php
- Bundle/WidgetMapBundle/Resources/config/services.yml
Bugfix
Fixes #806 
Add new Command to identify broken WidgetMaps
Isolate WidgetMap.getChildren method in an external service and log (CRITICAL) when WidgetMap are in conflict.
NO
> New Command and Logs to find Widgetmap conflicts

- Bundle/WidgetMapBundle/Manager/WidgetMapManager.php
- Tests/Features/WidgetMap/widgetMapTemplate.feature
Bugfix
Fix issue when a widget map is deleted in template and have children in inherited pages
Fixes #817
NO
> Widget map deletion children issue

- doc/setup.md
documentation
This PR improves documentation of the setup guide
The FosUserBundle routes was not declared so there was no way to login 
NO
> Add missing fosub routes in documentation

- Bundle/BlogBundle/Entity/Tag.php
- Bundle/BlogBundle/Resources/translations/victoire.en.xliff
- Bundle/BlogBundle/Resources/translations/victoire.es.xliff
- Bundle/BlogBundle/Resources/translations/victoire.fr.xliff
Feature
This PR fixes #841.
NO
---
This is useful to show tags on a blog article with the following query:
JOIN item.articles article WHERE article = :currentEntity
The `listing-widget/Victoire/Widget/ListingBundle/Resources/views/_showItem.html.twig` file must be modified (for example by creating a theme) in order to display only the `title` of Tag:
{{ item.title }}
> Make Blog > Tag a BusinessEntity

- Bundle/BlogBundle/Entity/Tag.php
- Bundle/BlogBundle/Resources/translations/victoire.en.xliff
- Bundle/BlogBundle/Resources/translations/victoire.es.xliff
- Bundle/BlogBundle/Resources/translations/victoire.fr.xliff
Feature
This PR fixes #841.
NO
---
This is useful to show tags on a blog article with the following query:
JOIN item.articles article WHERE article = :currentEntity
The `listing-widget/Victoire/Widget/ListingBundle/Resources/views/_showItem.html.twig` file must be modified (for example by creating a theme) in order to display only the `title` of Tag:
{{ item.title }}
> Blog > Tag is now a BusinessEntity

- Tests/Features/Page/error.feature
Bugfix
When accessing a page with a bad locale as parameter, the ErrorController forwarded to the victoire ErrorPage with the bad locale, throwing an Exception that was handled by the ErrorPageController, leading to a cyclic error.
With this PR, when the locale is unknown by victoire, it is replaced by the default locale
NO
> use default locale in errorPage if the given one is not known

- Bundle/WidgetMapBundle/Entity/WidgetMap.php
Bugfix
With no check on addWidget method, it could occur that a WidgetMap has two times the same Widget
NO
> avoid to add a widget already set in a widgetmap

- dependencies.md
gpc_magic_quotes setting was removed in v5.4 and is just ignored since then. 
No need to mention it, just confuses folks.
documentation
This PR improves documentation of dependencies
NO
> Removed gpc_magic_quotes ini setting

- doc/setup.md
Installations instruction were missing the BazingaJsTranslationBundle stuff. 
I added the needed line in AppKernel and the dump command before the `assetic:dump`
Assetic breaks when the file was not dumped before.
Documentation
Fixes broken `assetic:dump` command when following installation instructions
NO
> Add BazingaJsTranslationBundle stuff to setup.md

- Bundle/BlogBundle/Manager/ArticleManager.php
Bugfix
Fix issue than prevents article creation in blog when project extend victoire user model rather than victoire user entity.
The entity extends the model so it should not break anything
NO
> Use the model rather than the entity

- Bundle/BlogBundle/Manager/ArticleManager.php
- Bundle/CoreBundle/Resources/config/assetic_injector.json
- Bundle/CoreBundle/Resources/views/Layout/layout.html.twig
- behat.yml.dist
Bugfix
- Reorder Contexts to reset schema, then load fixture, then generate viewReferences
- Removes from assetic_injector cdn assets
- Use User model rather than the entity
NO
> Merge patchs from 2.2 into 2.3

- Bundle/WidgetMapBundle/Warmer/WidgetDataWarmer.php
Bugfix
Since optimization of widget data, the ordered relationships are ignored. So all list widgets or any other widgets use drag and drop to control the item, do not display the correct order in the view
NO
> implement OrderBy support in widgetDataWarmer

- Bundle/BlogBundle/Resources/views/Blog/Tabs/_links.html.twig
Bugfix
No PR opened, but when you install Victoire 2.3 on SF 3.2 you can't access to the blog section due to a deprecated syntax on twig.
> fix twig deprecated

- Bundle/I18nBundle/DependencyInjection/VictoireI18nExtension.php
- Bundle/TwigBundle/DependencyInjection/VictoireTwigExtension.php
Bugfix
In twig ~2.0, globals can be modified but not declared after initialization, leading to exceptions like:
```
Unable to add global "victoire_i18n_available_locales" as the runtime or the extensions have already been initialized.
```
To solve this, I ask DependencyInjection to insert these globals at bundle initialization.
NO
> insert twig globals at bundle boot

- Bundle/BlogBundle/Resources/views/Blog/Tabs/_articles.html.twig
Feature
This PR brings support of automatic change of locale when editing blog articles.
When editing an article in another language that the current language, the default tab was not open. This PR fixes this problem.
See #904 and #906.
NO
Thanks to @Charlie-Lucas!
> Fix bug with locale on blog articles list

- Bundle/WidgetBundle/Model/WidgetManager.php
Bugfix
Fixes a fatal error that occurs only on PHP 7.0.4-7ubuntu2.1:
> PHP Fatal error:  Cannot use Victoire\\Bundle\\WidgetBundle\\Entity\\Widget as Widget because the name is already in use in /…/vendor/victoire/victoire/Bundle/WidgetBundle/Model/WidgetManager.php on line 23,
NO
> Fix error "Widget […] name is already in use"

- Bundle/CoreBundle/Command/WidgetCssGenerateCommand.php
Bugfix
The progress helper was removed: https://symfony.com/doc/current/components/console/helpers/progresshelper.html
YES
> instantiate ProgressBar because the helper does not exists anymore

- Bundle/WidgetMapBundle/Warmer/WidgetDataWarmer.php
When manipulating a huge blog widget data warmer was throwing "Nesting level too deep".
Now we will use strict comparaison to avoid this kind of error on recursive object.
NO
> Use strict comparaison to avoid error with huge object

- composer.json
Fix error with uncompatible declaration of
`Victoire\Bundle\TwigBundle\Controller\ExceptionController::showAction()`
Bugfix
Fixes an exception that occured with Symfony 2.8:
> Whoops, looks like something went wrong.
> 1/1 ContextErrorException in ExceptionController.php line 18:
> 
> Warning: Declaration of Victoire\Bundle\TwigBundle\Controller\ExceptionController::showAction(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\Debug\Exception\FlattenException $exception, Symfony\Component\HttpKernel\Log\DebugLoggerInterface $logger = NULL, $_format = 'html') should be compatible with Symfony\Bundle\TwigBundle\Controller\ExceptionController::showAction(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpKernel\Exception\FlattenException $exception, …
> Update "symfony/twig-bundle" to "~3.0"

- Bundle/TemplateBundle/Resources/views/Template/index.html.twig
Bugfix
Exception message:
> An exception has been thrown during the rendering of a template (&quot;Notice: Undefined index: macros&quot;)
According to [Twig documentation](https://twig.symfony.com/doc/2.x/tags/macro.html):
> When you want to use a macro in another macro from the same file, you need to import it locally
So I added a use in the macro.
NO
> Add import in Twig macro

- Bundle/BusinessEntityBundle/Entity/Traits/BusinessEntityTrait.php
Bugfix
Fixes exception that break page rendering when a widget call a property that doesn't exist.
NO
> Avoid error when a widget call a missing property

- .codacy.yml
CI fix
Exclude external vendors from codacy checks
> exclude external vendors from codacy checks

- .codacy.yml
Bugfix
fix codacy checkstyle by excluding external vendors
> exclude vendors from codacy

- Bundle/BlogBundle/Form/ArticleSettingsType.php
- Bundle/BlogBundle/Form/BlogSettingsType.php
- Bundle/PageBundle/Form/PageSettingsType.php
- Bundle/PageBundle/Resources/translations/victoire.en.xliff
- Bundle/PageBundle/Resources/translations/victoire.es.xliff
- Bundle/PageBundle/Resources/translations/victoire.fr.xliff
- Bundle/SitemapBundle/Controller/SitemapController.php
- Bundle/SitemapBundle/Resources/views/Sitemap/_sitemapItem.html.twig
- Bundle/SitemapBundle/Resources/views/Sitemap/reorganize.html.twig
- Bundle/UIBundle/Resources/public/stylesheets/main-front.css
- Bundle/UIBundle/Resources/stylesheets/front/components/sitemap/_sitemap.scss
Feature
This PR brings improvement of the sitemap:
- Show unpublished pages in the list
- Show status as text
NO
---
Here is the result:
> Feature: Display unpublished pages in Victoire sitemap

- Bundle/BlogBundle/Filter/CategoryFilter.php
Bugfix
Fixes exception:
>  Class 'Victoire\Bundle\BlogBundle\Filter\BlogCategory' does not exist 
NO
> Bugfix: Fix typo in CategoryFilter

- Bundle/SeoBundle/Entity/PageSeo.php
> Feature #1010: Increase “metaDescription” length to 230

- Bundle/WidgetBundle/Model/WidgetManager.php
- Bundle/WidgetMapBundle/Entity/WidgetMap.php
- Bundle/WidgetMapBundle/Manager/WidgetMapManager.php
- Tests/Features/WidgetMap/widgetMapTemplate.feature
> Inverse method order to avoid error when flushing non-persisted element
> 
> ## Type
> Bugfix
> 
> ## Purpose
> Change method call order to avoid error when persisting a view with a new widget map
> 
> ## BC Break
> NO
Replaces #982.
> Fix test assertion was true with beginning condition

- Bundle/SitemapBundle/Command/GenerateCommand.php
- Bundle/SitemapBundle/Controller/SitemapController.php
- Bundle/SitemapBundle/Domain/Export/SitemapExportHandler.php
- Bundle/SitemapBundle/Resources/config/services.yml
- Bundle/SitemapBundle/Resources/views/Sitemap/sitemap.xml.twig
Bugfix
On a site with many pages, the sitemap may take more than 30 seconds to generate. This PR adds a CLI command to store the content of the sitemap in redis.
NO
> Add CLI to generate sitemap

- Bundle/SitemapBundle/Domain/Export/SitemapExportHandler.php
- Bundle/SitemapBundle/Resources/views/Sitemap/sitemap.xml.twig
Bugfix
Fixes an error when using the command on a website that has pages without `publishedAt` data:
```bash
$ php bin/console victoire:generate:sitemap --env=prod --no-debug -vvv
[Symfony\Component\Debug\Exception\FatalThrowableError]  
Call to a member function format() on null               
Exception trace:
() at /var/www/preprod.wweeddoo.com/releases/20180430115502/vendor/victoire/victoire/Bundle/SitemapBundle/Domain/Export/SitemapExportHandler.php:94
Victoire\Bundle\SitemapBundle\Domain\Export\SitemapExportHandler->serialize() at /var/www/preprod.wweeddoo.com/releases/20180430115502/vendor/victoire/victoire/Bundle/SitemapBundle/Command/GenerateCommand.php:42
Victoire\Bundle\SitemapBundle\Command\GenerateCommand->execute() at 
```
NO
> Fix issues with sitemap export

- Bundle/CoreBundle/Repository/ViewRepository.php
Bugfix
The StatefulRepository on `clearInstance` call reset the `mainAlias` property.
The use of the `getInstance` property needs to be used to avoid problems (eg. on the sitemap generation)
NO
> Use getInstance method instead of native createQueryBuilder

- Bundle/PageBundle/Helper/PageHelper.php
feature
This PR brings support of permanent redirections (301) to SeoBundle Redirections
NO
> [2.2] set redirect response status to permanent

- Bundle/PageBundle/Resources/views/Page/settings.html.twig
Bugfix
Same as #1077 because the code is the same on the 2.3 branch: https://github.com/Victoire/victoire/blob/cda2cbcf64c032106a78bc157b73c6b1ce0ffae9/Bundle/CoreBundle/Form/ViewType.php#L127
NO
> [2.3] fix error with settings roles

- Bundle/PageBundle/Helper/PageHelper.php
Bugfix
Fixes PHPDoc because it breaks the PHPStan analysis of a project that call one of these methods.
Error reported by PHPStan:
```
------ -------------------------------------------------------------------- 
Line   src/AppBundle/Controller/AppController.php                      
------ -------------------------------------------------------------------- 
40     Parameter #2 $layout of method                                      
Victoire\Bundle\PageBundle\Helper\PageHelper::renderPage() expects  
null, string given.                                                 
```
NO
> PageHelper: Fix PHPDoc

- Bundle/PageBundle/Resources/views/Page/settings.html.twig
Bugfix
Fixes an exception:
> Neither the property "roles" nor one of the methods "roles()", "getroles()"/"isroles()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView".
> 500 Internal Server Error - Twig_Error_Runtime 
>  in vendor/victoire/victoire/Bundle/PageBundle/Resources/views/Page/settings.html.twig at line 22  - 
This error is due to the fact that the `roles` field is added only if the user as the `ROLE_VICTOIRE_DEVELOPER` role: https://github.com/Victoire/victoire/blob/023e778c859699cc4992b5f05cb9b864c4e2f0e4/Bundle/CoreBundle/Form/ViewType.php#L126
An user with the `ROLE_VICTOIRE` role can access to this modal form, but an error is thrown if the user doesn't have the `ROLE_VICTOIRE_DEVELOPER` role.
NO
> [2.2] Fix error with settings roles

- doc/setup.md
MediaBundle require LiipImagine to display image but routing is missing
Bugfix
Fixes thumbnail uri in Media Library
NO
> MediaBundle need LiipImagine

- Bundle/MediaBundle/Resources/config/liip_imagine.yml
Bugfix
Filesystem is already the default loader and this syntax make errors 
https://symfony.com/doc/2.0/bundles/LiipImagineBundle/data-loader/filesystem.html
NO
> fix liip_imagine config

- composer.json
Bugfix
This PR allows to install more recent versions of swift mailer 
NO
> raise symfony/swiftmailer-bundle dependancy

- Bundle/SeoBundle/Entity/PageSeoTranslation.php
feature
Google now allow dynamic meta description size. 320 char will be less prohibitive than 230
NO
> increase meta description field

- Bundle/WidgetBundle/Model/WidgetManager.php
Bugfix
It does fix an old bug we've seeked for a long time... This is why sometimes, some `VirtualBusinessPages` were persisted in database while it never should. 
NO
> transform (Virtual) BusinessPage

- doc/setup.md
Wrong path for AppKernel.php
Documentation
This PR improves documentation of setup
NO
> Fixing the path AppKernel path
